### PR TITLE
Some fixes and additions

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
Additions
- @agnostic-apollo's `sudo`
- @laraib07's `androfetch`
- A function `lit-update` to update the system + ZSH stuff.

Fixes
- the `lit-colors` is now a function instead of alias, handles internet connectivity stuff.
- the backup is expanded to more files, improved logic.

### CODE REVIEW

**Comment by agnostic-apollo** [comment]
Thanks for the include :)

Let me know if any support is required. I'll likely be adding the `--update` flag in the next version.

**Comment by AvinashReddy3108** [comment]
> I'll likely be adding the `--update` flag in the next version.

That will be great!

**Comment by rihaq** [comment]
>  I'll likely be adding the `--update` flag in the next version.
Can you add `--update` flag now?

**Comment by agnostic-apollo** [comment]
> Can you add --update flag now?

Will try taking time out for it.

**Pull request merged**
